# Generated by Django 5.1.6 on 2025-03-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_usedproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedproduct',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='usedproduct',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Great', 'Great'), ('Excellent', 'Excellent')], default='Good', max_length=10),
        ),
        migrations.AddField(
            model_name='usedproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='used_products/'),
        ),
        migrations.AddField(
            model_name='usedproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='used_products/'),
        ),
        migrations.AddField(
            model_name='usedproduct',
            name='phone_number',
            field=models.CharField(default='0000000000', help_text='Enter your contact number', max_length=15),
        ),
    ]
