# Generated by Django 5.1.6 on 2025-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_image_usedproduct_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedproduct',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('great', 'Great'), ('excellent', 'Excellent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usedproduct',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='used_products/'),
        ),
        migrations.AlterField(
            model_name='usedproduct',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
