# Generated by Django 5.1.6 on 2025-03-12 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_billingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('cod', 'Cash on Delivery')], max_length=10),
        ),
    ]
